## static_countries
UPDATE static_countries SET cn_short_lt='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_lt='Jungtiniai Arabų Emyratai' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_lt='Afganistanas' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_lt='Antigva ir Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_lt='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_lt='Albanija' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_lt='Armėnija' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_lt='Nyderlandų Antilai' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_lt='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_lt='Antarktida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_lt='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_lt='Amerikos Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_lt='Austrija' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_lt='Australija' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_lt='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_lt='Azerbaidžanas' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_lt='Bosnija ir Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_lt='Barbadosas' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_lt='Bangladešas' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_lt='Belgija' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_lt='Burkina Fasas' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_lt='Bulgarija' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_lt='Bahreinas' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_lt='Burundis' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_lt='Beninas' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_lt='Bermudai' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_lt='Brunėjus Darusalamas' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_lt='Bolivija' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_lt='Brazilija' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_lt='Bahamos' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_lt='Butanas' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_lt='Bouvet sala' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_lt='Botsvana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_lt='Baltarusija' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_lt='Belizas' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_lt='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_lt='Kokosų salos (Kylingas)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_lt='Kongo Demokratinė Respublika' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_lt='Centrine Afrikos Respublika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_lt='Kongas' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_lt='Šveicarija' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_lt='Dramblio kaulo krantas' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_lt='Kuko salos' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_lt='Čilė' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_lt='Kamerūnas' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_lt='Kinija' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_lt='Kolumbija' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_lt='Kosta Rika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_lt='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_lt='Žaliasis Kyšulys' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_lt='Kalėdų sala' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_lt='Kipras' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_lt='Čekijos Respublika' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_lt='Vokietija' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_lt='Džibutis' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_lt='Danija' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_lt='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_lt='Dominikos Respublika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_lt='Alžyras' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_lt='Ekvadoras' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_lt='Estija' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_lt='Egiptas' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_lt='Vakarų Sachara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_lt='Eritrėja' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_lt='Ispanija' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_lt='Etiopija' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_lt='Suomija' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_lt='Fidžis' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_lt='Folklando salos' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_lt='Mikronezija' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_lt='Farerų salos' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_lt='Prancūzija' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_lt='Gabonas' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_lt='Didžioji Britanija' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_lt='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_lt='Gruzija' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_lt='Prancūzijos Gviana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_lt='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_lt='Gibraltaras' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_lt='Grenlandija' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_lt='Gambija' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_lt='Gvinėja' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_lt='Gvadelupa' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_lt='Pusiaujo Gvinėja' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_lt='Graikija' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_lt='Pietų Džordžija ir Pietų Sandvičo salos' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_lt='Gvatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_lt='Guamas' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_lt='Bisau Gvinėja' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_lt='Gajana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_lt='Honkongas S.A.R., Kinija' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_lt='Hondūras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_lt='Kroatija' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_lt='Haitis' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_lt='Vengrija' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_lt='Indonezija' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_lt='Airija' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_lt='Izraelis' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_lt='Indija' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_lt='Britų Indijos vandenyno teritorija' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_lt='Irakas' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_lt='Iranas' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_lt='Islandija' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_lt='Italija' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_lt='Jamaika' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_lt='Jordanas' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_lt='Japonija' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_lt='Kenija' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_lt='Kirgizija' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_lt='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_lt='Kiribatis' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_lt='Komorai' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_lt='Sent Kitsas ir Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_lt='Korėjos Liaudies Demokratinė Respublika' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_lt='Korėjos Respublika' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_lt='Kuveitas' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_lt='Kaimanų salos' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_lt='Kazachstanas' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_lt='Laosas' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_lt='Libanas' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_lt='Sent Liucija' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_lt='Lichtenšteinas' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_lt='Šri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_lt='Liberija' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_lt='Lesotas' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_lt='Lietuva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_lt='Liuksemburgas' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_lt='Latvija' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_lt='Libija' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_lt='Marokas' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_lt='Monakas' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_lt='Moldovos Respublika' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_lt='Madagaskaras' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_lt='Maršalo salos' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_lt='Šiaurės Makedonija' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_lt='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_lt='Mianmaras' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_lt='Mongolija' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_lt='Makao S.A.R., Kinija' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_lt='Šiaurinės Marianų salos' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_lt='Martinika' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_lt='Mauritanija' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_lt='Montserratas' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_lt='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_lt='Mauricijus' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_lt='Maldyvai' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_lt='Malavis' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_lt='Meksika' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_lt='Malaizija' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_lt='Mozambikas' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_lt='Namibija' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_lt='Naujoji Kaledonija' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_lt='Nigeris' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_lt='Norfolko sala' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_lt='Nigerija' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_lt='Nikaragva' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_lt='Nyderlandai' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_lt='Norvegija' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_lt='Nepalas' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_lt='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_lt='Naujas' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_lt='Naujoji Zelandija' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_lt='Omanas' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_lt='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_lt='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_lt='Prancūzų Polinezija' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_lt='Papua Naujoji Gvinėja' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_lt='Filipinai' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_lt='Pakistanas' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_lt='Lenkija' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_lt='Sen Pjeras ir Mikelonas' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_lt='Pitkernas' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_lt='Puerto Rikas' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_lt='Portugalija' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_lt='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_lt='Paragvajus' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_lt='Kataras' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_lt='Susijungimas' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_lt='Rumunija' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_lt='Rusijos Federacija' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_lt='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_lt='Saudo Arabija' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_lt='Saliamono salos' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_lt='Seišeliai' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_lt='Sudanas' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_lt='Švedija' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_lt='Singapūras' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_lt='Šv. Elena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_lt='Slovėnija' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_lt='Svalbardas ir Janas Mayenas' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_lt='Slovakija' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_lt='Siera Leonė' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_lt='San Marinas' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_lt='Senegalas' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_lt='Somalis' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_lt='Surinamas' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_lt='San Tomė ir Prinsipė' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_lt='Salvadoras' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_lt='Sirija' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_lt='Svazilandas' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_lt='Terkso ir Kaikoso salos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_lt='Čadas' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_lt='Prancūzijos pietinės ir Antarkties teritorijos' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_lt='Eiti' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_lt='Tailandas' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_lt='Tadžikistanas' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_lt='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_lt='Turkmėnistanas' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_lt='Tunisas' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_lt='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_lt='Rytų Timoras' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_lt='Turkija' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_lt='Trinidadas ir Tobagas' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_lt='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_lt='Taivanas' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_lt='Tanzanija' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_lt='Ukraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_lt='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_lt='Amerikos Okeanija' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_lt='Jungtinės Amerikos Valstijos' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_lt='Urugvajus' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_lt='Uzbekistanas' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_lt='Vatikano miestas' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_lt='Sent Vincentas ir Grenadinai' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_lt='Venesuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_lt='Britanijos mergelių salos' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_lt='Amerikos Mergelių salos' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_lt='Vietnamas' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_lt='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_lt='Wallis ir Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_lt='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_lt='Jemenas' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_lt='Majotas' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_lt='Pietų Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_lt='Zambija' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_lt='Zimbabvė' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_lt='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_lt='Serbija ir Juodkalnija' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_lt='Alandų salos' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_lt='Heard ir McDonald salos' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_lt='Juodkalnija' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_lt='Serbija' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_lt='Džersis' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_lt='Gernsis' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_lt='Meno sala' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_lt='Šventasis Martynas' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_lt='Šventasis Bartelemis' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_lt='Bonaire, Sint Eustatius ir Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_lt='Kiurasao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_lt='Šventasis Martenas' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_lt='Pietų Sudanas' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_lt='Kosovas' WHERE cn_iso_2='XK';
